services:
  app:
    build:
      context: .
      target: dev
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
    ports:
      - "3300:3000"
    command: ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
